// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAppTraefikConfigParams creates a new GetAppTraefikConfigParams object
// with the default values initialized.
func NewGetAppTraefikConfigParams() *GetAppTraefikConfigParams {
	var ()
	return &GetAppTraefikConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppTraefikConfigParamsWithTimeout creates a new GetAppTraefikConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppTraefikConfigParamsWithTimeout(timeout time.Duration) *GetAppTraefikConfigParams {
	var ()
	return &GetAppTraefikConfigParams{

		timeout: timeout,
	}
}

// NewGetAppTraefikConfigParamsWithContext creates a new GetAppTraefikConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppTraefikConfigParamsWithContext(ctx context.Context) *GetAppTraefikConfigParams {
	var ()
	return &GetAppTraefikConfigParams{

		Context: ctx,
	}
}

// NewGetAppTraefikConfigParamsWithHTTPClient creates a new GetAppTraefikConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppTraefikConfigParamsWithHTTPClient(client *http.Client) *GetAppTraefikConfigParams {
	var ()
	return &GetAppTraefikConfigParams{
		HTTPClient: client,
	}
}

/*GetAppTraefikConfigParams contains all the parameters to send to the API endpoint
for the get app traefik config operation typically these are written to a http.Request
*/
type GetAppTraefikConfigParams struct {

	/*AppName
	  App name from the `-a|--app` flag

	*/
	AppName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get app traefik config params
func (o *GetAppTraefikConfigParams) WithTimeout(timeout time.Duration) *GetAppTraefikConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app traefik config params
func (o *GetAppTraefikConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get app traefik config params
func (o *GetAppTraefikConfigParams) WithContext(ctx context.Context) *GetAppTraefikConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app traefik config params
func (o *GetAppTraefikConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get app traefik config params
func (o *GetAppTraefikConfigParams) WithHTTPClient(client *http.Client) *GetAppTraefikConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app traefik config params
func (o *GetAppTraefikConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the get app traefik config params
func (o *GetAppTraefikConfigParams) WithAppName(appName string) *GetAppTraefikConfigParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the get app traefik config params
func (o *GetAppTraefikConfigParams) SetAppName(appName string) {
	o.AppName = appName
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppTraefikConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
