// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRunConfigParams creates a new GetRunConfigParams object
// with the default values initialized.
func NewGetRunConfigParams() *GetRunConfigParams {
	var ()
	return &GetRunConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRunConfigParamsWithTimeout creates a new GetRunConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRunConfigParamsWithTimeout(timeout time.Duration) *GetRunConfigParams {
	var ()
	return &GetRunConfigParams{

		timeout: timeout,
	}
}

// NewGetRunConfigParamsWithContext creates a new GetRunConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRunConfigParamsWithContext(ctx context.Context) *GetRunConfigParams {
	var ()
	return &GetRunConfigParams{

		Context: ctx,
	}
}

// NewGetRunConfigParamsWithHTTPClient creates a new GetRunConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRunConfigParamsWithHTTPClient(client *http.Client) *GetRunConfigParams {
	var ()
	return &GetRunConfigParams{
		HTTPClient: client,
	}
}

/*GetRunConfigParams contains all the parameters to send to the API endpoint
for the get run config operation typically these are written to a http.Request
*/
type GetRunConfigParams struct {

	/*AppName
	  App name from the `-a|--app` flag

	*/
	AppName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get run config params
func (o *GetRunConfigParams) WithTimeout(timeout time.Duration) *GetRunConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get run config params
func (o *GetRunConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get run config params
func (o *GetRunConfigParams) WithContext(ctx context.Context) *GetRunConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get run config params
func (o *GetRunConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get run config params
func (o *GetRunConfigParams) WithHTTPClient(client *http.Client) *GetRunConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get run config params
func (o *GetRunConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the get run config params
func (o *GetRunConfigParams) WithAppName(appName string) *GetRunConfigParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the get run config params
func (o *GetRunConfigParams) SetAppName(appName string) {
	o.AppName = appName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRunConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
