// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAppsParams creates a new GetAppsParams object
// with the default values initialized.
func NewGetAppsParams() *GetAppsParams {
	var ()
	return &GetAppsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppsParamsWithTimeout creates a new GetAppsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppsParamsWithTimeout(timeout time.Duration) *GetAppsParams {
	var ()
	return &GetAppsParams{

		timeout: timeout,
	}
}

// NewGetAppsParamsWithContext creates a new GetAppsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppsParamsWithContext(ctx context.Context) *GetAppsParams {
	var ()
	return &GetAppsParams{

		Context: ctx,
	}
}

// NewGetAppsParamsWithHTTPClient creates a new GetAppsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppsParamsWithHTTPClient(client *http.Client) *GetAppsParams {
	var ()
	return &GetAppsParams{
		HTTPClient: client,
	}
}

/*GetAppsParams contains all the parameters to send to the API endpoint
for the get apps operation typically these are written to a http.Request
*/
type GetAppsParams struct {

	/*Hidden
	  Whether or not to show hidden apps

	*/
	Hidden *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get apps params
func (o *GetAppsParams) WithTimeout(timeout time.Duration) *GetAppsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get apps params
func (o *GetAppsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get apps params
func (o *GetAppsParams) WithContext(ctx context.Context) *GetAppsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get apps params
func (o *GetAppsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get apps params
func (o *GetAppsParams) WithHTTPClient(client *http.Client) *GetAppsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get apps params
func (o *GetAppsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHidden adds the hidden to the get apps params
func (o *GetAppsParams) WithHidden(hidden *bool) *GetAppsParams {
	o.SetHidden(hidden)
	return o
}

// SetHidden adds the hidden to the get apps params
func (o *GetAppsParams) SetHidden(hidden *bool) {
	o.Hidden = hidden
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Hidden != nil {

		// query param hidden
		var qrHidden bool
		if o.Hidden != nil {
			qrHidden = *o.Hidden
		}
		qHidden := swag.FormatBool(qrHidden)
		if qHidden != "" {
			if err := r.SetQueryParam("hidden", qHidden); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
