// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInstallPluginParams creates a new InstallPluginParams object
// with the default values initialized.
func NewInstallPluginParams() *InstallPluginParams {
	var ()
	return &InstallPluginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInstallPluginParamsWithTimeout creates a new InstallPluginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInstallPluginParamsWithTimeout(timeout time.Duration) *InstallPluginParams {
	var ()
	return &InstallPluginParams{

		timeout: timeout,
	}
}

// NewInstallPluginParamsWithContext creates a new InstallPluginParams object
// with the default values initialized, and the ability to set a context for a request
func NewInstallPluginParamsWithContext(ctx context.Context) *InstallPluginParams {
	var ()
	return &InstallPluginParams{

		Context: ctx,
	}
}

// NewInstallPluginParamsWithHTTPClient creates a new InstallPluginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInstallPluginParamsWithHTTPClient(client *http.Client) *InstallPluginParams {
	var ()
	return &InstallPluginParams{
		HTTPClient: client,
	}
}

/*InstallPluginParams contains all the parameters to send to the API endpoint
for the install plugin operation typically these are written to a http.Request
*/
type InstallPluginParams struct {

	/*PluginName*/
	PluginName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the install plugin params
func (o *InstallPluginParams) WithTimeout(timeout time.Duration) *InstallPluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the install plugin params
func (o *InstallPluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the install plugin params
func (o *InstallPluginParams) WithContext(ctx context.Context) *InstallPluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the install plugin params
func (o *InstallPluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the install plugin params
func (o *InstallPluginParams) WithHTTPClient(client *http.Client) *InstallPluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the install plugin params
func (o *InstallPluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPluginName adds the pluginName to the install plugin params
func (o *InstallPluginParams) WithPluginName(pluginName string) *InstallPluginParams {
	o.SetPluginName(pluginName)
	return o
}

// SetPluginName adds the pluginName to the install plugin params
func (o *InstallPluginParams) SetPluginName(pluginName string) {
	o.PluginName = pluginName
}

// WriteToRequest writes these params to a swagger request
func (o *InstallPluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pluginName
	if err := r.SetPathParam("pluginName", o.PluginName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
