// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aklinker1/miasma/package/models"
)

// ListPluginsReader is a Reader for the ListPlugins structure.
type ListPluginsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPluginsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPluginsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListPluginsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListPluginsOK creates a ListPluginsOK with default headers values
func NewListPluginsOK() *ListPluginsOK {
	return &ListPluginsOK{}
}

/*ListPluginsOK handles this case with default header values.

OK
*/
type ListPluginsOK struct {
	Payload []*models.Plugin
}

func (o *ListPluginsOK) Error() string {
	return fmt.Sprintf("[GET /api/plugins][%d] listPluginsOK  %+v", 200, o.Payload)
}

func (o *ListPluginsOK) GetPayload() []*models.Plugin {
	return o.Payload
}

func (o *ListPluginsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPluginsDefault creates a ListPluginsDefault with default headers values
func NewListPluginsDefault(code int) *ListPluginsDefault {
	return &ListPluginsDefault{
		_statusCode: code,
	}
}

/*ListPluginsDefault handles this case with default header values.

Unknown Error
*/
type ListPluginsDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the list plugins default response
func (o *ListPluginsDefault) Code() int {
	return o._statusCode
}

func (o *ListPluginsDefault) Error() string {
	return fmt.Sprintf("[GET /api/plugins][%d] listPlugins default  %+v", o._statusCode, o.Payload)
}

func (o *ListPluginsDefault) GetPayload() string {
	return o.Payload
}

func (o *ListPluginsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
