// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StopAppReader is a Reader for the StopApp structure.
type StopAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewStopAppNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewStopAppDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStopAppOK creates a StopAppOK with default headers values
func NewStopAppOK() *StopAppOK {
	return &StopAppOK{}
}

/*StopAppOK handles this case with default header values.

Stopped
*/
type StopAppOK struct {
}

func (o *StopAppOK) Error() string {
	return fmt.Sprintf("[POST /api/apps/{appName}/stop][%d] stopAppOK ", 200)
}

func (o *StopAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopAppNotFound creates a StopAppNotFound with default headers values
func NewStopAppNotFound() *StopAppNotFound {
	return &StopAppNotFound{}
}

/*StopAppNotFound handles this case with default header values.

Not Found
*/
type StopAppNotFound struct {
	Payload string
}

func (o *StopAppNotFound) Error() string {
	return fmt.Sprintf("[POST /api/apps/{appName}/stop][%d] stopAppNotFound  %+v", 404, o.Payload)
}

func (o *StopAppNotFound) GetPayload() string {
	return o.Payload
}

func (o *StopAppNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopAppDefault creates a StopAppDefault with default headers values
func NewStopAppDefault(code int) *StopAppDefault {
	return &StopAppDefault{
		_statusCode: code,
	}
}

/*StopAppDefault handles this case with default header values.

Unknown Error
*/
type StopAppDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the stop app default response
func (o *StopAppDefault) Code() int {
	return o._statusCode
}

func (o *StopAppDefault) Error() string {
	return fmt.Sprintf("[POST /api/apps/{appName}/stop][%d] stopApp default  %+v", o._statusCode, o.Payload)
}

func (o *StopAppDefault) GetPayload() string {
	return o.Payload
}

func (o *StopAppDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
