// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aklinker1/miasma/package/models"
)

// UninstallPluginReader is a Reader for the UninstallPlugin structure.
type UninstallPluginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UninstallPluginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUninstallPluginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUninstallPluginDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUninstallPluginOK creates a UninstallPluginOK with default headers values
func NewUninstallPluginOK() *UninstallPluginOK {
	return &UninstallPluginOK{}
}

/*UninstallPluginOK handles this case with default header values.

Created
*/
type UninstallPluginOK struct {
	Payload *models.Plugin
}

func (o *UninstallPluginOK) Error() string {
	return fmt.Sprintf("[DELETE /api/plugins/{pluginName}][%d] uninstallPluginOK  %+v", 200, o.Payload)
}

func (o *UninstallPluginOK) GetPayload() *models.Plugin {
	return o.Payload
}

func (o *UninstallPluginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Plugin)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUninstallPluginDefault creates a UninstallPluginDefault with default headers values
func NewUninstallPluginDefault(code int) *UninstallPluginDefault {
	return &UninstallPluginDefault{
		_statusCode: code,
	}
}

/*UninstallPluginDefault handles this case with default header values.

Unknown Error
*/
type UninstallPluginDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the uninstall plugin default response
func (o *UninstallPluginDefault) Code() int {
	return o._statusCode
}

func (o *UninstallPluginDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/plugins/{pluginName}][%d] uninstallPlugin default  %+v", o._statusCode, o.Payload)
}

func (o *UninstallPluginDefault) GetPayload() string {
	return o.Payload
}

func (o *UninstallPluginDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
