// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateAppEnvParams creates a new UpdateAppEnvParams object
// with the default values initialized.
func NewUpdateAppEnvParams() *UpdateAppEnvParams {
	var ()
	return &UpdateAppEnvParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAppEnvParamsWithTimeout creates a new UpdateAppEnvParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAppEnvParamsWithTimeout(timeout time.Duration) *UpdateAppEnvParams {
	var ()
	return &UpdateAppEnvParams{

		timeout: timeout,
	}
}

// NewUpdateAppEnvParamsWithContext creates a new UpdateAppEnvParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAppEnvParamsWithContext(ctx context.Context) *UpdateAppEnvParams {
	var ()
	return &UpdateAppEnvParams{

		Context: ctx,
	}
}

// NewUpdateAppEnvParamsWithHTTPClient creates a new UpdateAppEnvParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAppEnvParamsWithHTTPClient(client *http.Client) *UpdateAppEnvParams {
	var ()
	return &UpdateAppEnvParams{
		HTTPClient: client,
	}
}

/*UpdateAppEnvParams contains all the parameters to send to the API endpoint
for the update app env operation typically these are written to a http.Request
*/
type UpdateAppEnvParams struct {

	/*AppName
	  App name from the `-a|--app` flag

	*/
	AppName string
	/*NewEnv*/
	NewEnv interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update app env params
func (o *UpdateAppEnvParams) WithTimeout(timeout time.Duration) *UpdateAppEnvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update app env params
func (o *UpdateAppEnvParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update app env params
func (o *UpdateAppEnvParams) WithContext(ctx context.Context) *UpdateAppEnvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update app env params
func (o *UpdateAppEnvParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update app env params
func (o *UpdateAppEnvParams) WithHTTPClient(client *http.Client) *UpdateAppEnvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update app env params
func (o *UpdateAppEnvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the update app env params
func (o *UpdateAppEnvParams) WithAppName(appName string) *UpdateAppEnvParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the update app env params
func (o *UpdateAppEnvParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithNewEnv adds the newEnv to the update app env params
func (o *UpdateAppEnvParams) WithNewEnv(newEnv interface{}) *UpdateAppEnvParams {
	o.SetNewEnv(newEnv)
	return o
}

// SetNewEnv adds the newEnv to the update app env params
func (o *UpdateAppEnvParams) SetNewEnv(newEnv interface{}) {
	o.NewEnv = newEnv
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAppEnvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	if o.NewEnv != nil {
		if err := r.SetBodyParam(o.NewEnv); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
