// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aklinker1/miasma/package/models"
)

// UpdateAppConfigReader is a Reader for the UpdateAppConfig structure.
type UpdateAppConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAppConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAppConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateAppConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateAppConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewUpdateAppConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAppConfigOK creates a UpdateAppConfigOK with default headers values
func NewUpdateAppConfigOK() *UpdateAppConfigOK {
	return &UpdateAppConfigOK{}
}

/*UpdateAppConfigOK handles this case with default header values.

OK
*/
type UpdateAppConfigOK struct {
	Payload *models.AppConfig
}

func (o *UpdateAppConfigOK) Error() string {
	return fmt.Sprintf("[PUT /api/apps/{appName}/config][%d] updateAppConfigOK  %+v", 200, o.Payload)
}

func (o *UpdateAppConfigOK) GetPayload() *models.AppConfig {
	return o.Payload
}

func (o *UpdateAppConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppConfigBadRequest creates a UpdateAppConfigBadRequest with default headers values
func NewUpdateAppConfigBadRequest() *UpdateAppConfigBadRequest {
	return &UpdateAppConfigBadRequest{}
}

/*UpdateAppConfigBadRequest handles this case with default header values.

Bad Request
*/
type UpdateAppConfigBadRequest struct {
	Payload string
}

func (o *UpdateAppConfigBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/apps/{appName}/config][%d] updateAppConfigBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateAppConfigBadRequest) GetPayload() string {
	return o.Payload
}

func (o *UpdateAppConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppConfigNotFound creates a UpdateAppConfigNotFound with default headers values
func NewUpdateAppConfigNotFound() *UpdateAppConfigNotFound {
	return &UpdateAppConfigNotFound{}
}

/*UpdateAppConfigNotFound handles this case with default header values.

Not Found
*/
type UpdateAppConfigNotFound struct {
	Payload string
}

func (o *UpdateAppConfigNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/apps/{appName}/config][%d] updateAppConfigNotFound  %+v", 404, o.Payload)
}

func (o *UpdateAppConfigNotFound) GetPayload() string {
	return o.Payload
}

func (o *UpdateAppConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppConfigDefault creates a UpdateAppConfigDefault with default headers values
func NewUpdateAppConfigDefault(code int) *UpdateAppConfigDefault {
	return &UpdateAppConfigDefault{
		_statusCode: code,
	}
}

/*UpdateAppConfigDefault handles this case with default header values.

Unknown Error
*/
type UpdateAppConfigDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the update app config default response
func (o *UpdateAppConfigDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAppConfigDefault) Error() string {
	return fmt.Sprintf("[PUT /api/apps/{appName}/config][%d] updateAppConfig default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAppConfigDefault) GetPayload() string {
	return o.Payload
}

func (o *UpdateAppConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
