// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aklinker1/miasma/package/models"
)

// UpdateAppTraefikConfigReader is a Reader for the UpdateAppTraefikConfig structure.
type UpdateAppTraefikConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAppTraefikConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAppTraefikConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateAppTraefikConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewUpdateAppTraefikConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAppTraefikConfigOK creates a UpdateAppTraefikConfigOK with default headers values
func NewUpdateAppTraefikConfigOK() *UpdateAppTraefikConfigOK {
	return &UpdateAppTraefikConfigOK{}
}

/*UpdateAppTraefikConfigOK handles this case with default header values.

Created
*/
type UpdateAppTraefikConfigOK struct {
	Payload *models.TraefikPluginConfig
}

func (o *UpdateAppTraefikConfigOK) Error() string {
	return fmt.Sprintf("[PUT /api/plugins/traefik/{appId}][%d] updateAppTraefikConfigOK  %+v", 200, o.Payload)
}

func (o *UpdateAppTraefikConfigOK) GetPayload() *models.TraefikPluginConfig {
	return o.Payload
}

func (o *UpdateAppTraefikConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TraefikPluginConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppTraefikConfigBadRequest creates a UpdateAppTraefikConfigBadRequest with default headers values
func NewUpdateAppTraefikConfigBadRequest() *UpdateAppTraefikConfigBadRequest {
	return &UpdateAppTraefikConfigBadRequest{}
}

/*UpdateAppTraefikConfigBadRequest handles this case with default header values.

Traefik plugin is not installed
*/
type UpdateAppTraefikConfigBadRequest struct {
	Payload string
}

func (o *UpdateAppTraefikConfigBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/plugins/traefik/{appId}][%d] updateAppTraefikConfigBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateAppTraefikConfigBadRequest) GetPayload() string {
	return o.Payload
}

func (o *UpdateAppTraefikConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppTraefikConfigDefault creates a UpdateAppTraefikConfigDefault with default headers values
func NewUpdateAppTraefikConfigDefault(code int) *UpdateAppTraefikConfigDefault {
	return &UpdateAppTraefikConfigDefault{
		_statusCode: code,
	}
}

/*UpdateAppTraefikConfigDefault handles this case with default header values.

Unknown Error
*/
type UpdateAppTraefikConfigDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the update app traefik config default response
func (o *UpdateAppTraefikConfigDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAppTraefikConfigDefault) Error() string {
	return fmt.Sprintf("[PUT /api/plugins/traefik/{appId}][%d] updateAppTraefikConfig default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAppTraefikConfigDefault) GetPayload() string {
	return o.Payload
}

func (o *UpdateAppTraefikConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
