// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateAppParams creates a new UpdateAppParams object
// with the default values initialized.
func NewUpdateAppParams() *UpdateAppParams {
	var ()
	return &UpdateAppParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAppParamsWithTimeout creates a new UpdateAppParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAppParamsWithTimeout(timeout time.Duration) *UpdateAppParams {
	var ()
	return &UpdateAppParams{

		timeout: timeout,
	}
}

// NewUpdateAppParamsWithContext creates a new UpdateAppParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAppParamsWithContext(ctx context.Context) *UpdateAppParams {
	var ()
	return &UpdateAppParams{

		Context: ctx,
	}
}

// NewUpdateAppParamsWithHTTPClient creates a new UpdateAppParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAppParamsWithHTTPClient(client *http.Client) *UpdateAppParams {
	var ()
	return &UpdateAppParams{
		HTTPClient: client,
	}
}

/*UpdateAppParams contains all the parameters to send to the API endpoint
for the update app operation typically these are written to a http.Request
*/
type UpdateAppParams struct {

	/*AppName
	  App name from the `-a|--app` flag

	*/
	AppName string
	/*NewImage
	  A new image to base the app off of

	*/
	NewImage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update app params
func (o *UpdateAppParams) WithTimeout(timeout time.Duration) *UpdateAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update app params
func (o *UpdateAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update app params
func (o *UpdateAppParams) WithContext(ctx context.Context) *UpdateAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update app params
func (o *UpdateAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update app params
func (o *UpdateAppParams) WithHTTPClient(client *http.Client) *UpdateAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update app params
func (o *UpdateAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppName adds the appName to the update app params
func (o *UpdateAppParams) WithAppName(appName string) *UpdateAppParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the update app params
func (o *UpdateAppParams) SetAppName(appName string) {
	o.AppName = appName
}

// WithNewImage adds the newImage to the update app params
func (o *UpdateAppParams) WithNewImage(newImage *string) *UpdateAppParams {
	o.SetNewImage(newImage)
	return o
}

// SetNewImage adds the newImage to the update app params
func (o *UpdateAppParams) SetNewImage(newImage *string) {
	o.NewImage = newImage
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	if o.NewImage != nil {

		// query param newImage
		var qrNewImage string
		if o.NewImage != nil {
			qrNewImage = *o.NewImage
		}
		qNewImage := qrNewImage
		if qNewImage != "" {
			if err := r.SetQueryParam("newImage", qNewImage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
