services:
  proxy:
    image: nginx:alpine
    volumes:
      - './docker/nginx-proxy.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 3000:80

  frontend:
    build:
      dockerfile: docker/Dockerfile.dev.frontend
      context: .
    volumes:
      - ./web/tsconfig.node.json:/build/web/tsconfig.node.json
      - ./web/vite.config.ts:/build/web/vite.config.ts
      - ./web/tsconfig.json:/build/web/tsconfig.json
      - ./web/index.html:/build/web/index.html
      - ./web/postcss.config.js:/build/web/postcss.config.js
      - ./web/tailwind.config.js:/build/web/tailwind.config.js
      - ./web/src:/build/web/src
      - ./web/dist:/build/web/dist
    ports:
      - 3001:3000

  backend:
    build:
      dockerfile: docker/Dockerfile.dev.backend
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/modd.conf:/build/modd.conf
      - ./cmd/server:/build/cmd/server
      - ./internal/shared:/build/internal/shared
      - ./internal/server:/build/internal/server
      - ./package/models:/build/package/models
      - ./web/dist:/build/web/dist
    ports:
      - 3002:3000
    environment:
      VERSION: ${VERSION}-dev
      BUILD: ${BUILD}
      BUILD_HASH: ${BUILD_HASH}
      BUILD_DATE: ${BUILD_DATE}
