// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppList: typeof import('./../components/AppList.vue')['default']
    AppListItem: typeof import('./../components/AppListItem.vue')['default']
    DrawerScaffold: typeof import('./../components/DrawerScaffold.vue')['default']
    IMdiCross: typeof import('~icons/mdi/cross')['default']
    IMdiCube: typeof import('~icons/mdi/cube')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiMenuRound: typeof import('~icons/mdi/menu-round')['default']
    IMdiMenuRounded: typeof import('~icons/mdi/menu-rounded')['default']
    IMdiMoreVert: typeof import('~icons/mdi/more-vert')['default']
    IMdiOpenInNew: typeof import('~icons/mdi/open-in-new')['default']
    IMdiPlay: typeof import('~icons/mdi/play')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiReload: typeof import('~icons/mdi/reload')['default']
    IMdiRoundMenu: typeof import('~icons/mdi/round-menu')['default']
    IMdiStart: typeof import('~icons/mdi/start')['default']
    IMdiStop: typeof import('~icons/mdi/stop')['default']
    IMdiToolbox: typeof import('~icons/mdi/toolbox')['default']
    Loading: typeof import("../components/LoadingIndicator.vue")["default"];
    LoadingIndicator: typeof import('./../components/LoadingIndicator.vue')['default']
  }
}

export {}
