# Setup
FROM node:16-alpine
WORKDIR /build
RUN apk --no-cache add curl
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
ADD package.json pnpm-lock.yaml pnpm-workspace.yaml ./
ADD web/package.json web/package.json
ADD web/pnpm-lock.yaml web/pnpm-lock.yaml
RUN pnpm install --frozen-lockfile
WORKDIR /build/web
CMD pnpm dev
