// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AppInput app input
//
// swagger:model AppInput
type AppInput struct {

	// A simple label to track what apps are related
	Group string `json:"group,omitempty" gorm:"index"`

	// Whether or not the app is hidden during regular requests
	Hidden bool `json:"hidden,omitempty"`

	// The image and tag the application runs
	// Required: true
	Image string `json:"image"`

	// The apps name, used in the CLI with the `-a|--app` flag
	// Required: true
	Name string `json:"name"`
}

// Validate validates this app input
func (m *AppInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInput) validateImage(formats strfmt.Registry) error {

	if err := validate.RequiredString("image", "body", string(m.Image)); err != nil {
		return err
	}

	return nil
}

func (m *AppInput) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInput) UnmarshalBinary(b []byte) error {
	var res AppInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
