// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AppEdit app edit
//
// swagger:model AppEdit
type AppEdit struct {

	// A simple label to track what apps are related
	Group string `json:"group,omitempty"`

	// Whether or not the app is returned during regular requests
	Hidden bool `json:"hidden,omitempty"`

	// The apps name, used in the CLI with the `-a|--app` flag
	// Required: true
	Name string `json:"name"`
}

// Validate validates this app edit
func (m *AppEdit) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppEdit) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppEdit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppEdit) UnmarshalBinary(b []byte) error {
	var res AppEdit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
