/* tslint:disable */
/* eslint-disable */
/**
 * Miasma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 *
 * @export
 * @interface App
 */
export interface App {
  /**
   *
   * @type {string}
   * @memberof App
   */
  id: string;
  /**
   * The apps name, used in the CLI with the `-a|--app` flag
   * @type {string}
   * @memberof App
   */
  name: string;
  /**
   * A simple label to track what apps are related
   * @type {string}
   * @memberof App
   */
  group?: string;
  /**
   * The image and tag the application runs
   * @type {string}
   * @memberof App
   */
  image?: string;
  /**
   * Whether or not the app is returned during regular requests
   * @type {boolean}
   * @memberof App
   */
  hidden?: boolean;
}
/**
 *
 * @export
 * @interface AppEdit
 */
export interface AppEdit {
  /**
   * The apps name, used in the CLI with the `-a|--app` flag
   * @type {string}
   * @memberof AppEdit
   */
  name: string;
  /**
   * A simple label to track what apps are related
   * @type {string}
   * @memberof AppEdit
   */
  group?: string;
  /**
   * Whether or not the app is returned during regular requests
   * @type {boolean}
   * @memberof AppEdit
   */
  hidden?: boolean;
}
/**
 *
 * @export
 * @interface AppInput
 */
export interface AppInput {
  /**
   * The apps name, used in the CLI with the `-a|--app` flag
   * @type {string}
   * @memberof AppInput
   */
  name: string;
  /**
   * A simple label to track what apps are related
   * @type {string}
   * @memberof AppInput
   */
  group?: string;
  /**
   * The image and tag the application runs
   * @type {string}
   * @memberof AppInput
   */
  image: string;
  /**
   * Whether or not the app is hidden during regular requests
   * @type {boolean}
   * @memberof AppInput
   */
  hidden?: boolean;
}
/**
 *
 * @export
 * @interface AppWithStatus
 */
export interface AppWithStatus {
  /**
   * The apps name, used in the CLI with the `-a|--app` flag
   * @type {string}
   * @memberof AppWithStatus
   */
  name: string;
  /**
   * A simple label to track what apps are related
   * @type {string}
   * @memberof AppWithStatus
   */
  group?: string;
  /**
   * The published ports for the app
   * @type {Array<string>}
   * @memberof AppWithStatus
   */
  ports: Array<string>;
  /**
   * If the app has routing, a simple string representing that route
   * @type {string}
   * @memberof AppWithStatus
   */
  routing?: string;
  /**
   * Whether or not the application is running, stopped, or starting up
   * @type {string}
   * @memberof AppWithStatus
   */
  status: string;
  /**
   * The number of instances running vs what should be running
   * @type {string}
   * @memberof AppWithStatus
   */
  instances?: string;
}
/**
 *
 * @export
 * @interface Health
 */
export interface Health {
  /**
   * Miasma\'s current version
   * @type {string}
   * @memberof Health
   */
  version: string;
  /**
   * The version of docker running on the host, or null if docker is not running
   * @type {string}
   * @memberof Health
   */
  dockerVersion: string;
  /**
   *
   * @type {HealthSwarm}
   * @memberof Health
   */
  swarm: HealthSwarm;
}
/**
 * The info about the docker swarm if the host running miasma is apart of one. If it is not apart of a swarm, it returns `null`
 * @export
 * @interface HealthSwarm
 */
export interface HealthSwarm {
  /**
   * The swarm\'s ID
   * @type {string}
   * @memberof HealthSwarm
   */
  id?: string;
  /**
   * The command for a node to run to join the swarm
   * @type {string}
   * @memberof HealthSwarm
   */
  joinCommand?: string;
  /**
   * UTC timestamps when the swarm was created
   * @type {string}
   * @memberof HealthSwarm
   */
  createdAt?: string;
  /**
   * UTC timestamps when the swarm was last updated
   * @type {string}
   * @memberof HealthSwarm
   */
  updatedAt?: string;
}
/**
 * All the properties that define how the application runs in docker
 * @export
 * @interface InputRunConfig
 */
export interface InputRunConfig {
  /**
   *
   * @type {Set<number>}
   * @memberof InputRunConfig
   */
  targetPorts?: Set<number>;
  /**
   *
   * @type {Set<number>}
   * @memberof InputRunConfig
   */
  publishedPorts?: Set<number>;
  /**
   *
   * @type {Set<string>}
   * @memberof InputRunConfig
   */
  placement?: Set<string>;
  /**
   * volume bindings for the app
   * @type {Array<RunConfigVolume>}
   * @memberof InputRunConfig
   */
  volumes?: Array<RunConfigVolume>;
  /**
   *
   * @type {Set<string>}
   * @memberof InputRunConfig
   */
  networks?: Set<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof InputRunConfig
   */
  command?: Array<string>;
}
/**
 *
 * @export
 * @interface InputTraefikPluginConfig
 */
export interface InputTraefikPluginConfig {
  /**
   * Describes the hostname the app is served at (\"test.domain.com\")
   * @type {string}
   * @memberof InputTraefikPluginConfig
   */
  host?: string | null;
  /**
   * The path at a given host the app can be reached from (\"/api\"). It should start with a \"/\"
   * @type {string}
   * @memberof InputTraefikPluginConfig
   */
  path?: string | null;
  /**
   * Instead of using `host` and/or `path`, you can specify the exact rule Traefik will use to route to the app. See [Traefik\'s documentation]() for how to use this field. This field takes priority over `host` and `path`
   * @type {string}
   * @memberof InputTraefikPluginConfig
   */
  traefikRule?: string | null;
}
/**
 *
 * @export
 * @interface Plugin
 */
export interface Plugin {
  /**
   * The plugin\'s name. It can be used to install a plugin
   * @type {string}
   * @memberof Plugin
   */
  name: string;
  /**
   * Whether or not the plugin is installed
   * @type {boolean}
   * @memberof Plugin
   */
  installed: boolean;
}
/**
 * All the properties that define how the application runs in docker
 * @export
 * @interface RunConfig
 */
export interface RunConfig {
  /**
   * The ID of the app the run config is for
   * @type {string}
   * @memberof RunConfig
   */
  appId: string;
  /**
   * The currently running image digest (hash). Used internally when running applications instead of the tag because the when a new image is pushed, the tag stays the same but the digest changes
   * @type {string}
   * @memberof RunConfig
   */
  imageDigest: string;
  /**
   * The ports that the app is listening to inside the container. If no target ports are specified, then the container should respect the `PORT` env var.
   * @type {Set<number>}
   * @memberof RunConfig
   */
  targetPorts?: Set<number>;
  /**
   * The ports that you access the app through in the swarm. This field can, and should be left empty. Miasma automatically manages assigning published ports between 3001-4999. If you need to specify a port, make sure it\'s outside that range or the port has not been taken. Plugins have set ports starting with 4000, so avoid 4000-4020 if you want to add a plugin at a later date. If these ports are ever cleared, the app will continue using the same ports it was published to before, so that the ports don\'t change unnecessarily. If you removed it to clear a port for another app/plugin, make sure to restart the app and a new, random port will be allocated for the app, freeing the old port
   * @type {Set<number>}
   * @memberof RunConfig
   */
  publishedPorts?: Set<number>;
  /**
   * The placement constraints specifying which nodes the app will be ran on. Any valid value for the [`--constraint` flag](https://docs.docker.com/engine/swarm/services/#placement-constraints) is valid item in this list
   * @type {Set<string>}
   * @memberof RunConfig
   */
  placement?: Set<string>;
  /**
   * volume bindings for the app
   * @type {Array<RunConfigVolume>}
   * @memberof RunConfig
   */
  volumes?: Array<RunConfigVolume>;
  /**
   * A list of other apps that the service communicates with using their service name and docker\'s internal DNS. Services don\'t have to be two way; only the service that accesses the other needs the other network added
   * @type {Set<string>}
   * @memberof RunConfig
   */
  networks?: Set<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof RunConfig
   */
  command?: Array<string>;
}
/**
 *
 * @export
 * @interface RunConfigVolume
 */
export interface RunConfigVolume {
  /**
   * The volume name or directory on the host that the data is stored in
   * @type {string}
   * @memberof RunConfigVolume
   */
  Source?: string;
  /**
   * The path inside the container that the data is served from
   * @type {string}
   * @memberof RunConfigVolume
   */
  Target?: string;
}
/**
 *
 * @export
 * @interface TraefikPluginConfig
 */
export interface TraefikPluginConfig {
  /**
   *
   * @type {string}
   * @memberof TraefikPluginConfig
   */
  appId?: string;
  /**
   * Describes the hostname the app is served at (\"test.domain.com\")
   * @type {string}
   * @memberof TraefikPluginConfig
   */
  host?: string | null;
  /**
   * The path at a given host the app can be reached from (\"/api\"). It should start with a \"/\"
   * @type {string}
   * @memberof TraefikPluginConfig
   */
  path?: string | null;
  /**
   * Instead of using `host` and/or `path`, you can specify the exact rule Traefik will use to route to the app. See [Traefik\'s documentation]() for how to use this field. This field takes priority over `host` and `path`
   * @type {string}
   * @memberof TraefikPluginConfig
   */
  traefikRule?: string | null;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Create and start a new app
     * @param {AppInput} [app]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createApp: async (app?: AppInput, options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/apps`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        app,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Stop and delete an app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteApp: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('deleteApp', 'appName', appName);
      const localVarPath = `/api/apps/{appName}`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Edit the app details
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {AppEdit} newApp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    editApp: async (appName: string, newApp: AppEdit, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('editApp', 'appName', appName);
      // verify required parameter 'newApp' is not null or undefined
      assertParamExists('editApp', 'newApp', newApp);
      const localVarPath = `/api/apps/{appName}`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        newApp,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get an app by name
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getApp: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('getApp', 'appName', appName);
      const localVarPath = `/api/apps/{appName}`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary get an app\'s environment variables
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAppEnv: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('getAppEnv', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/env`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get an app\'s routing config
     * @param {string} appId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAppTraefikConfig: async (appId: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appId' is not null or undefined
      assertParamExists('getAppTraefikConfig', 'appId', appId);
      const localVarPath = `/api/plugins/traefik/{appId}`.replace(
        `{${'appId'}}`,
        encodeURIComponent(String(appId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPlugin: async (pluginName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'pluginName' is not null or undefined
      assertParamExists('getPlugin', 'pluginName', pluginName);
      const localVarPath = `/api/plugins/{pluginName}`.replace(
        `{${'pluginName'}}`,
        encodeURIComponent(String(pluginName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary get an app\'s current config
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRunConfig: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('getRunConfig', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/config`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Standard health check endpoint that checks all the service\'s statuses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheck: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/health`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Install (and start) a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    installPlugin: async (pluginName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'pluginName' is not null or undefined
      assertParamExists('installPlugin', 'pluginName', pluginName);
      const localVarPath = `/api/plugins/{pluginName}`.replace(
        `{${'pluginName'}}`,
        encodeURIComponent(String(pluginName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List all the running apps
     * @param {boolean} [hidden] Whether or not to show hidden apps
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listApps: async (hidden?: boolean, options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/apps`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (hidden !== undefined) {
        localVarQueryParameter['hidden'] = hidden;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List all available plugins and if they are installed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listPlugins: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/plugins`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Reload
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reloadApp: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('reloadApp', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/reload`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Removes an app\'s routing config
     * @param {string} appId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeAppTraefikConfig: async (appId: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appId' is not null or undefined
      assertParamExists('removeAppTraefikConfig', 'appId', appId);
      const localVarPath = `/api/plugins/traefik/{appId}`.replace(
        `{${'appId'}}`,
        encodeURIComponent(String(appId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary start the app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startApp: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('startApp', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/start`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary stop the app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    stopApp: async (appName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('stopApp', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/stop`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Stop and uninstall a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uninstallPlugin: async (pluginName: string, options: any = {}): Promise<RequestArgs> => {
      // verify required parameter 'pluginName' is not null or undefined
      assertParamExists('uninstallPlugin', 'pluginName', pluginName);
      const localVarPath = `/api/plugins/{pluginName}`.replace(
        `{${'pluginName'}}`,
        encodeURIComponent(String(pluginName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary update an app\'s env
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {{ [key: string]: object; }} [newEnv]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAppEnv: async (
      appName: string,
      newEnv?: { [key: string]: object },
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('updateAppEnv', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/env`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        newEnv,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update an app\'s routing config
     * @param {string} appId
     * @param {InputTraefikPluginConfig} [newTraefikConfig]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAppTraefikConfig: async (
      appId: string,
      newTraefikConfig?: InputTraefikPluginConfig,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'appId' is not null or undefined
      assertParamExists('updateAppTraefikConfig', 'appId', appId);
      const localVarPath = `/api/plugins/traefik/{appId}`.replace(
        `{${'appId'}}`,
        encodeURIComponent(String(appId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        newTraefikConfig,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary update an app\'s config
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {InputRunConfig} [newRunConfig]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateRunConfig: async (
      appName: string,
      newRunConfig?: InputRunConfig,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('updateRunConfig', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/config`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        newRunConfig,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary pull the app\'s image and restart it
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {string} [newImage] A new image to base the app off of
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    upgradeApp: async (
      appName: string,
      newImage?: string,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'appName' is not null or undefined
      assertParamExists('upgradeApp', 'appName', appName);
      const localVarPath = `/api/apps/{appName}/upgrade`.replace(
        `{${'appName'}}`,
        encodeURIComponent(String(appName)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (newImage !== undefined) {
        localVarQueryParameter['newImage'] = newImage;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Create and start a new app
     * @param {AppInput} [app]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createApp(
      app?: AppInput,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<App>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createApp(app, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Stop and delete an app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteApp(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<App>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteApp(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Edit the app details
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {AppEdit} newApp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async editApp(
      appName: string,
      newApp: AppEdit,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<App>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.editApp(appName, newApp, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Get an app by name
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getApp(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<App>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getApp(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary get an app\'s environment variables
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAppEnv(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAppEnv(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Get an app\'s routing config
     * @param {string} appId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAppTraefikConfig(
      appId: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TraefikPluginConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAppTraefikConfig(appId, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Get a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPlugin(
      pluginName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Plugin>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPlugin(pluginName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary get an app\'s current config
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getRunConfig(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RunConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getRunConfig(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Standard health check endpoint that checks all the service\'s statuses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async healthCheck(
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Health>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Install (and start) a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async installPlugin(
      pluginName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Plugin>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.installPlugin(pluginName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary List all the running apps
     * @param {boolean} [hidden] Whether or not to show hidden apps
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listApps(
      hidden?: boolean,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AppWithStatus>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listApps(hidden, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary List all available plugins and if they are installed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listPlugins(
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Plugin>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listPlugins(options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Reload
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reloadApp(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.reloadApp(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Removes an app\'s routing config
     * @param {string} appId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async removeAppTraefikConfig(
      appId: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TraefikPluginConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.removeAppTraefikConfig(
        appId,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary start the app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async startApp(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.startApp(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary stop the app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async stopApp(
      appName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.stopApp(appName, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Stop and uninstall a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async uninstallPlugin(
      pluginName: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Plugin>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.uninstallPlugin(
        pluginName,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary update an app\'s env
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {{ [key: string]: object; }} [newEnv]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateAppEnv(
      appName: string,
      newEnv?: { [key: string]: object },
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppEnv(
        appName,
        newEnv,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Update an app\'s routing config
     * @param {string} appId
     * @param {InputTraefikPluginConfig} [newTraefikConfig]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateAppTraefikConfig(
      appId: string,
      newTraefikConfig?: InputTraefikPluginConfig,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TraefikPluginConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppTraefikConfig(
        appId,
        newTraefikConfig,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary update an app\'s config
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {InputRunConfig} [newRunConfig]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateRunConfig(
      appName: string,
      newRunConfig?: InputRunConfig,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RunConfig>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateRunConfig(
        appName,
        newRunConfig,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary pull the app\'s image and restart it
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {string} [newImage] A new image to base the app off of
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async upgradeApp(
      appName: string,
      newImage?: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.upgradeApp(
        appName,
        newImage,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @summary Create and start a new app
     * @param {AppInput} [app]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createApp(app?: AppInput, options?: any): AxiosPromise<App> {
      return localVarFp.createApp(app, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Stop and delete an app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteApp(appName: string, options?: any): AxiosPromise<App> {
      return localVarFp.deleteApp(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Edit the app details
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {AppEdit} newApp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    editApp(appName: string, newApp: AppEdit, options?: any): AxiosPromise<App> {
      return localVarFp.editApp(appName, newApp, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Get an app by name
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getApp(appName: string, options?: any): AxiosPromise<App> {
      return localVarFp.getApp(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary get an app\'s environment variables
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAppEnv(appName: string, options?: any): AxiosPromise<object> {
      return localVarFp.getAppEnv(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Get an app\'s routing config
     * @param {string} appId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAppTraefikConfig(appId: string, options?: any): AxiosPromise<TraefikPluginConfig> {
      return localVarFp
        .getAppTraefikConfig(appId, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Get a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPlugin(pluginName: string, options?: any): AxiosPromise<Plugin> {
      return localVarFp.getPlugin(pluginName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary get an app\'s current config
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRunConfig(appName: string, options?: any): AxiosPromise<RunConfig> {
      return localVarFp.getRunConfig(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Standard health check endpoint that checks all the service\'s statuses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthCheck(options?: any): AxiosPromise<Health> {
      return localVarFp.healthCheck(options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Install (and start) a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    installPlugin(pluginName: string, options?: any): AxiosPromise<Plugin> {
      return localVarFp
        .installPlugin(pluginName, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary List all the running apps
     * @param {boolean} [hidden] Whether or not to show hidden apps
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listApps(hidden?: boolean, options?: any): AxiosPromise<Array<AppWithStatus>> {
      return localVarFp.listApps(hidden, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary List all available plugins and if they are installed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listPlugins(options?: any): AxiosPromise<Array<Plugin>> {
      return localVarFp.listPlugins(options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Reload
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reloadApp(appName: string, options?: any): AxiosPromise<void> {
      return localVarFp.reloadApp(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Removes an app\'s routing config
     * @param {string} appId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeAppTraefikConfig(appId: string, options?: any): AxiosPromise<TraefikPluginConfig> {
      return localVarFp
        .removeAppTraefikConfig(appId, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary start the app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startApp(appName: string, options?: any): AxiosPromise<void> {
      return localVarFp.startApp(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary stop the app
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    stopApp(appName: string, options?: any): AxiosPromise<void> {
      return localVarFp.stopApp(appName, options).then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Stop and uninstall a plugin
     * @param {string} pluginName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uninstallPlugin(pluginName: string, options?: any): AxiosPromise<Plugin> {
      return localVarFp
        .uninstallPlugin(pluginName, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary update an app\'s env
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {{ [key: string]: object; }} [newEnv]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAppEnv(
      appName: string,
      newEnv?: { [key: string]: object },
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .updateAppEnv(appName, newEnv, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary Update an app\'s routing config
     * @param {string} appId
     * @param {InputTraefikPluginConfig} [newTraefikConfig]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAppTraefikConfig(
      appId: string,
      newTraefikConfig?: InputTraefikPluginConfig,
      options?: any,
    ): AxiosPromise<TraefikPluginConfig> {
      return localVarFp
        .updateAppTraefikConfig(appId, newTraefikConfig, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary update an app\'s config
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {InputRunConfig} [newRunConfig]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateRunConfig(
      appName: string,
      newRunConfig?: InputRunConfig,
      options?: any,
    ): AxiosPromise<RunConfig> {
      return localVarFp
        .updateRunConfig(appName, newRunConfig, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @summary pull the app\'s image and restart it
     * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
     * @param {string} [newImage] A new image to base the app off of
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    upgradeApp(appName: string, newImage?: string, options?: any): AxiosPromise<void> {
      return localVarFp
        .upgradeApp(appName, newImage, options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @summary Create and start a new app
   * @param {AppInput} [app]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public createApp(app?: AppInput, options?: any) {
    return DefaultApiFp(this.configuration)
      .createApp(app, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Stop and delete an app
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public deleteApp(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .deleteApp(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Edit the app details
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {AppEdit} newApp
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public editApp(appName: string, newApp: AppEdit, options?: any) {
    return DefaultApiFp(this.configuration)
      .editApp(appName, newApp, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get an app by name
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getApp(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .getApp(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary get an app\'s environment variables
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getAppEnv(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .getAppEnv(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get an app\'s routing config
   * @param {string} appId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getAppTraefikConfig(appId: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .getAppTraefikConfig(appId, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get a plugin
   * @param {string} pluginName
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getPlugin(pluginName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .getPlugin(pluginName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary get an app\'s current config
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getRunConfig(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .getRunConfig(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Standard health check endpoint that checks all the service\'s statuses
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public healthCheck(options?: any) {
    return DefaultApiFp(this.configuration)
      .healthCheck(options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Install (and start) a plugin
   * @param {string} pluginName
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public installPlugin(pluginName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .installPlugin(pluginName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List all the running apps
   * @param {boolean} [hidden] Whether or not to show hidden apps
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public listApps(hidden?: boolean, options?: any) {
    return DefaultApiFp(this.configuration)
      .listApps(hidden, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List all available plugins and if they are installed
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public listPlugins(options?: any) {
    return DefaultApiFp(this.configuration)
      .listPlugins(options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Reload
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public reloadApp(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .reloadApp(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Removes an app\'s routing config
   * @param {string} appId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public removeAppTraefikConfig(appId: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .removeAppTraefikConfig(appId, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary start the app
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public startApp(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .startApp(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary stop the app
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public stopApp(appName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .stopApp(appName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Stop and uninstall a plugin
   * @param {string} pluginName
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public uninstallPlugin(pluginName: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .uninstallPlugin(pluginName, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary update an app\'s env
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {{ [key: string]: object; }} [newEnv]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public updateAppEnv(appName: string, newEnv?: { [key: string]: object }, options?: any) {
    return DefaultApiFp(this.configuration)
      .updateAppEnv(appName, newEnv, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update an app\'s routing config
   * @param {string} appId
   * @param {InputTraefikPluginConfig} [newTraefikConfig]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public updateAppTraefikConfig(
    appId: string,
    newTraefikConfig?: InputTraefikPluginConfig,
    options?: any,
  ) {
    return DefaultApiFp(this.configuration)
      .updateAppTraefikConfig(appId, newTraefikConfig, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary update an app\'s config
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {InputRunConfig} [newRunConfig]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public updateRunConfig(appName: string, newRunConfig?: InputRunConfig, options?: any) {
    return DefaultApiFp(this.configuration)
      .updateRunConfig(appName, newRunConfig, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary pull the app\'s image and restart it
   * @param {string} appName App name from the &#x60;-a|--app&#x60; flag
   * @param {string} [newImage] A new image to base the app off of
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public upgradeApp(appName: string, newImage?: string, options?: any) {
    return DefaultApiFp(this.configuration)
      .upgradeApp(appName, newImage, options)
      .then(request => request(this.axios, this.basePath));
  }
}
