name: Publish Docker Image
on:
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  publish:
    runs-on: ubuntu-22.04
    needs: [validate]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Bump and Tag
        id: bump
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          pnpx changelogen@latest --release
          git push
          git push --tags
          echo "version=$(node -pe 'require("./package.json").version')" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: aklinker1/miasma
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.bump.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ steps.bump.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: GitHub Release
        run: pnpx changelogen@latest gh release --token ${{ secrets.GITHUB_TOKEN }}
