name: Publish Server
on: [workflow_dispatch]

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  release:
    runs-on: ubuntu-22.04
    needs: [validate]
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      nextVersion: ${{ steps.changelog.outputs.nextVersion }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - id: changelog
        name: Generate Changelog
        uses: ./.github/actions/generate-changelog
        with:
          message: Download via [Docker Hub](https://hub.docker.com/r/aklinker1/miasma)
          module: Server
          scopes: api, ui

      - name: Bump Version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          node -p -e "
            const meta = JSON.parse(\`$(cat meta.json)\`);
            meta.serverVersion = '${{ steps.changelog.outputs.nextVersion }}';
            JSON.stringify(meta, null, 2);
          " > meta.json
          echo "Updated meta.json:"
          cat ./meta.json
          git add ./meta.json
          git commit -m "chore(release): server-v${{ steps.changelog.outputs.nextVersion }}"
          git push

      - name: Create Tag
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git tag "server-v${{ steps.changelog.outputs.nextVersion }}"
          git push --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: server-v${{ steps.changelog.outputs.nextVersion }}
          release_name: Server v${{ steps.changelog.outputs.nextVersion }}
          body: ${{ steps.changelog.outputs.changelog }}

  publish:
    uses: ./.github/workflows/upload-server-to-docker-hub.yml
    needs: [release]
    if: ${{ needs.release.outputs.skipped == 'false' }}
    with:
      ref: server-v${{ needs.release.outputs.nextVersion }}
      publishTags: --tag aklinker1/miasma:nightly --tag aklinker1/miasma:latest --tag aklinker1/miasma:${{ needs.release.outputs.nextVersion }}
    secrets: inherit
