name: Publish Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: web

      # run build script
      - name: Build VuePress site
        run: pnpm build
        working-directory: docs

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
